version: 2
updates: 
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "dependabot/*"
    schedule:
      interval: weekly